package com.DSAndAlgo;
import java.util.*;
import com.sun.source.doctree.SystemPropertyTree;

public class Main {
    public static void main(String[] args){
        int[] nums = {8, -7, 2, 5, 3, 1};
        int target = 10;
        PairSum pairsum = new PairSum();
        System.out.println("Finding the pair for the given target using Brute Force");
        printArray(pairsum.pairSumBruteForce(nums, target));
        System.out.println("");
        System.out.println("Finding the pair for the given target using Sorting");
        printArray(pairsum.pairsumSort(nums,target));
        System.out.println("");
        System.out.println("Finding the pair for the given target using HashMap");
        printArray(pairsum.pairsumSort(nums,target));
        System.out.println("");
        SubArrayzero subArrayzero = new SubArrayzero();
        int[] nums2 = {8, -8, 2, 5, 3, 1};
        printArray(nums2);
        System.out.println(subArrayzero.subArray(nums2));
        System.out.println();
        int[] nums3 = { 1, 2, 3, 4, 4 };
        printArray(nums3);
        Duplicate duplicate = new Duplicate();
        System.out.println(duplicate.duplicateSet(nums3));
        System.out.println(duplicate.duplicateHashing(nums3));
        System.out.println(duplicate.duplicateSum(nums3));
        System.out.println(duplicate.duplicateXOR(nums3));
        System.out.println(duplicate.duplicateArray(nums3));
        System.out.println();
        int[] nums4 = { 1, 0, 1, 1, 1, 0, 0, 1 };
        printArray(nums4);
        BinaryArrLinear binaryArrLinear = new BinaryArrLinear();
        printArray(binaryArrLinear.binaryLinearBrute(nums4));
        printArray(binaryArrLinear.binaryLinearWithoutCount(nums4));
        printArray(binaryArrLinear.binaryLinearQuickSort(nums4));
        int[] x = { 1, 4, 7, 8, 10 };
        int[] y = { 2, 3, 9 };
        printArray(x);
        printArray(y);
        MergeTwoSortedArrays merge = new MergeTwoSortedArrays();
        merge.mergeSortedArrays(x,y);
        printArray(x);
        printArray(y);
        int[] nums5= {1, 2, 3, 4, 5, 6, 7};
        printArray(nums5);
        AlternateHighAndLow alternateHighAndLow = new AlternateHighAndLow();
        alternateHighAndLow.alternateHighandLowOpt(nums5);
        printArray(nums5);
        int[] nums6 = { 3, 4, -7, 3, 1, 3, 1, -4, -2, -2 };
        printArray(nums6);
        SubArrayZeroSum subArrayZeroSum = new SubArrayZeroSum();
        subArrayZeroSum.printAllSubArraysBrute(nums6);
        System.out.println();
        subArrayZeroSum.printAllSubArrays(nums6);
        System.out.println();
        IdenticalTrees identicalTrees = new IdenticalTrees();
        identicalTrees.createTree();
        int[] nums7 = {9,7,3,1,6,4,8};
        printArray(nums7);
        LinearSearch linearSearch = new LinearSearch();
        System.out.println("The given element is present at " + linearSearch.linearSearch(nums7,7));
        Arrays.sort(nums7);
        printArray(nums7);
        BinarySearch binarySearch = new BinarySearch();
        System.out.println("The given element is present at " + linearSearch.linearSearch(nums7,7));
        System.out.println("----------------Bubble Sort-----------------");
        BubbleSort bubbleSort = new BubbleSort();
        printArray(bubbleSort.bubbleSort(nums7));
        System.out.println("----------------Insertion Sort-----------------");
        InsertionSort insertionSort = new InsertionSort();
        printArray(insertionSort.insertionSort(nums7));
        System.out.println("----------------Selection Sort-----------------");
        SelectionSort selectionSort = new SelectionSort();
        printArray(selectionSort.selectionSort(nums7));
        System.out.println("----------------Quick Sort-----------------");
        QuickSort quickSort = new QuickSort();
        printArray(quickSort.quickSort(nums7,0,nums7.length - 1));
        System.out.println("----------------Merge Sort-----------------");
        MergeSort mergeSort = new MergeSort();
        //printArray(mergeSort.mergeSort(nums7,0,nums7.length - 1));
        int[] nums9 = {3,2,4,7,10,6,5};
        RemoveEvenIntegers removeEvenIntegers = new RemoveEvenIntegers();
        printArray(removeEvenIntegers.removeEvenIntegers(nums9));
        int[] nums10 = {2,11,5,10,7,8};
        ReverseArray reverseArray = new ReverseArray();
        printArray(reverseArray.revese(nums10));
        int[] nums11 = {5,9,3,15,1,2};
        MinimumValue minimumValue = new MinimumValue();
        System.out.println(minimumValue.minimum(nums11));
        int[] nums12 = {12,34,2,34,33,1};
        SecondMaximum secondMaximum = new SecondMaximum();
        System.out.println(secondMaximum.secondMaximum(nums12));
        int[] nums13 = {0,1,0,4,12};
        MoveZerosEnd moveZerosEnd = new MoveZerosEnd();
        printArray(moveZerosEnd.moveZerosEnd(nums13));
        int[] nums14 = {5,9,3,10};
        ResizeArray resizeArray = new ResizeArray();
        printArray(resizeArray.resizeArray(nums14,10));
        int[] nums15 = {2,4,1,8,6,3,7};
        MissingNumber missingNumber = new MissingNumber();
        System.out.println(missingNumber.missingNumber(nums15));
        String palindromeString = "madam";
        Palindrome palindrome = new Palindrome();
        System.out.println(palindrome.palindrome(palindromeString));
        SinglyLinkedList singlyLinkedList = new SinglyLinkedList();
        singlyLinkedList.print(singlyLinkedList.createLinkedList());
        System.out.println(singlyLinkedList.count(singlyLinkedList.createLinkedList()));
        singlyLinkedList.print(singlyLinkedList.insertAtBegin(singlyLinkedList.createLinkedList(),8));
        singlyLinkedList.print(singlyLinkedList.insertAtEnd(singlyLinkedList.createLinkedList(),10));
        singlyLinkedList.print(singlyLinkedList.insertAtPos(singlyLinkedList.createLinkedList(),10,3));
        singlyLinkedList.print(singlyLinkedList.deleteAtFirst(singlyLinkedList.createLinkedList()));
        singlyLinkedList.print(singlyLinkedList.deleteAtEnd(singlyLinkedList.createLinkedList()));
        singlyLinkedList.print(singlyLinkedList.deleteAtPos(singlyLinkedList.createLinkedList(),3));
        System.out.println(singlyLinkedList.searchElement(singlyLinkedList.createLinkedList(),4));
        singlyLinkedList.print(singlyLinkedList.reverse(singlyLinkedList.createLinkedList()));
        System.out.println(singlyLinkedList.middleNode(singlyLinkedList.createLinkedList()));
        System.out.println(singlyLinkedList.LastNthNode(singlyLinkedList.createLinkedList(),2));
        singlyLinkedList.print(singlyLinkedList.removeDuplicateSorted(singlyLinkedList.createLinkedList()));
        singlyLinkedList.print(singlyLinkedList.insertSorted(singlyLinkedList.createLinkedList(),2));
        singlyLinkedList.print(singlyLinkedList.removeKey(singlyLinkedList.createLinkedList(),1));
        Stack stack = new Stack();
        stack.push(2);
        stack.push(8);
        stack.push(5);
        stack.push(7);
        stack.print();
        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.peek());
        System.out.println(stack.length());
        ReverseString reverseString = new ReverseString();
        System.out.println(reverseString.reverseString("abcd"));
        int[] nums16 = {4,7,3,4,8,1};
        printArray(nums16);
        NextGreater nextGreater = new NextGreater();
        printArray(nextGreater.nextGreaterElementBrute(nums16));
        int[] nums17 = {4,7,3,4,8,1};
        printArray(nextGreater.nextGreaterStack(nums17));
        BalanceParenthesis balanceParenthesis = new BalanceParenthesis();
        System.out.println(balanceParenthesis.balanceParenthesis("{([])}"));
    }

    public static void printArray(int[] arr){
        for(int i = 0;i < arr.length;i++){
            System.out.print(arr[i] + " ");
        }
        System.out.println();
    }
}
